# .streamlit/secrets.toml
[api_keys]
alpha_vantage = "EODDV06QW3D9CSN5Y"
fred = "55b3fef39c2b4454f916d78e1212eaa6Y"

[google]
sheet_url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSxQl9YLTYhjlocSSPdEWkk7f_iMtoa9IFZ5mo57310jgHnqA2I4-ETc-4U8yZ_15XO2cMflRVfXgZ-/pub?output=csv"
